export interface WorkerTemplate {
  name: string;
  role: string;
  department: string;
  persona: string;
  tools: string[];
  is_manager: boolean;
}

export interface CompanyTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  departments: string[];
  workers: WorkerTemplate[];
  kpis: string[];
  inventoryCategories: string[];
}

export const COMPANY_TEMPLATES: Record<string, CompanyTemplate> = {
  saas: {
    id: "saas",
    name: "SaaS Company",
    description: "Software-as-a-Service business with subscriptions, MRR tracking, and customer success",
    icon: "💻",
    color: "from-blue-600 to-cyan-600",
    departments: ["Executive", "Finance", "Sales", "Operations", "Human Resources", "Engineering", "Customer Success"],
    workers: [
      {
        name: "Sophia",
        role: "Chief of Staff",
        department: "Executive",
        persona: "Strategic thinker who orchestrates cross-department initiatives. Proactive, data-driven, and always sees the big picture. Speaks with authority but stays approachable.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "CFO",
        department: "Finance",
        persona: "Sharp financial mind with deep expertise in SaaS metrics. Tracks MRR, ARR, churn, and LTV obsessively. Explains complex financial concepts clearly. Data-driven and precise.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Sales Director",
        department: "Sales",
        persona: "Energetic and competitive sales leader. Pipeline-obsessed, always chasing the next deal. Uses CRM data to forecast and strategize. Motivating and results-oriented.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Operations Manager",
        department: "Operations",
        persona: "Methodical systems thinker who optimizes processes. Manages inventory, projects, and infrastructure with precision. Calm under pressure, detail-oriented.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "HR Director",
        department: "Human Resources",
        persona: "Empathetic people leader focused on culture and growth. Manages team dynamics, policies, and onboarding. Warm, inclusive, and highly organized.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["MRR", "ARR", "Churn Rate", "LTV", "CAC"],
    inventoryCategories: ["Subscription", "Add-on", "Service", "Professional Services"],
  },

  ecommerce: {
    id: "ecommerce",
    name: "E-Commerce",
    description: "Online retail business with inventory, orders, shipping, and customer management",
    icon: "🛒",
    color: "from-orange-600 to-pink-600",
    departments: ["Executive", "Finance", "Sales", "Operations", "Marketing", "Customer Success"],
    workers: [
      {
        name: "Sophia",
        role: "General Manager",
        department: "Executive",
        persona: "Experienced e-commerce leader who balances growth with profitability. Understands every aspect of the business from supply chain to customer experience.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance Controller",
        department: "Finance",
        persona: "E-commerce finance specialist tracking margins, payment processing, returns, and cash flow. Expert at unit economics and profitability analysis.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Marketing Director",
        department: "Marketing",
        persona: "Digital marketing expert focused on conversion optimization, ad spend ROI, and customer acquisition. Data-driven and creative.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "get_sales_forecast"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Supply Chain Manager",
        department: "Operations",
        persona: "Logistics expert managing inventory, warehousing, shipping, and vendor relationships. Obsessive about stock levels and delivery times.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Customer Experience Lead",
        department: "Customer Success",
        persona: "Customer-obsessed leader focused on satisfaction, reviews, returns, and loyalty programs. Empathetic and solution-oriented.",
        tools: ["list_customers", "get_customer", "send_email", "list_emails", "log_customer_interaction"],
        is_manager: false,
      },
    ],
    kpis: ["AOV", "Conversion Rate", "Return Rate", "Customer Acquisition Cost", "Repeat Purchase Rate"],
    inventoryCategories: ["Electronics", "Clothing", "Home & Garden", "Food & Beverage", "Accessories"],
  },

  restaurant: {
    id: "restaurant",
    name: "Restaurant / F&B",
    description: "Food and beverage business with menu management, purchasing, and staff scheduling",
    icon: "🍽️",
    color: "from-red-600 to-orange-600",
    departments: ["Executive", "Finance", "Kitchen", "Operations", "Human Resources"],
    workers: [
      {
        name: "Sophia",
        role: "Restaurant Manager",
        department: "Executive",
        persona: "Seasoned restaurant manager who keeps everything running smoothly. From front-of-house to back-of-house, she knows every detail.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Purchasing",
        department: "Finance",
        persona: "Food cost expert who tracks margins, vendor payments, and daily revenue. Negotiates with suppliers and manages the budget tightly.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Head Chef",
        department: "Kitchen",
        persona: "Creative and disciplined chef who manages the menu, food quality, and kitchen operations. Passionate about ingredients and consistency.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Floor Manager",
        department: "Operations",
        persona: "Customer-facing operations lead managing reservations, service quality, and daily operations. Ensures every guest has a great experience.",
        tools: ["list_customers", "create_customer", "log_customer_interaction", "list_projects", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "HR & Training",
        department: "Human Resources",
        persona: "People manager handling staff scheduling, training, compliance, and team morale. Creates a positive workplace culture.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["Daily Revenue", "Food Cost %", "Labor Cost %", "Average Check", "Table Turnover"],
    inventoryCategories: ["Proteins", "Vegetables", "Dairy", "Beverages", "Dry Goods", "Supplies"],
  },

  agency: {
    id: "agency",
    name: "Agency / Studio",
    description: "Creative or digital agency with project-based work, client management, and team utilization",
    icon: "🎨",
    color: "from-purple-600 to-pink-600",
    departments: ["Executive", "Finance", "Sales", "Creative", "Project Management"],
    workers: [
      {
        name: "Sophia",
        role: "Managing Director",
        department: "Executive",
        persona: "Agency leader balancing creative excellence with business growth. Expert at client relationships, team leadership, and strategic direction.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance Director",
        department: "Finance",
        persona: "Agency finance expert tracking billable hours, project profitability, and cash flow. Manages retainers, billing cycles, and vendor payments.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Business Development",
        department: "Sales",
        persona: "Charismatic BD lead who brings in new clients and grows existing accounts. Expert at proposals, pitches, and relationship building.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Project Manager",
        department: "Project Management",
        persona: "Detail-oriented PM who keeps projects on track, on budget, and on scope. Expert at resource allocation, timelines, and client communication.",
        tools: ["list_projects", "create_project", "create_task", "update_task_status", "list_products", "get_inventory_valuation"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Creative Director",
        department: "Creative",
        persona: "Visionary creative leader who sets the bar for design and content quality. Mentors the team and ensures brand consistency for all clients.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["Billable Hours", "Utilization Rate", "Project Margin", "Client Satisfaction", "Pipeline Value"],
    inventoryCategories: ["Design Assets", "Software Licenses", "Stock Photos", "Templates", "Equipment"],
  },

  consulting: {
    id: "consulting",
    name: "Consulting Firm",
    description: "Professional services firm with client engagements, proposals, and knowledge management",
    icon: "📊",
    color: "from-emerald-600 to-teal-600",
    departments: ["Executive", "Finance", "Business Development", "Delivery", "Research"],
    workers: [
      {
        name: "Sophia",
        role: "Managing Partner",
        department: "Executive",
        persona: "Strategic consulting leader with deep industry expertise. Drives firm strategy, key client relationships, and thought leadership.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance Partner",
        department: "Finance",
        persona: "Financial steward managing partner distributions, project economics, and firm profitability. Expert at engagement pricing and cost management.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "BD Director",
        department: "Business Development",
        persona: "Relationship-driven BD leader who builds and maintains client partnerships. Expert at proposals, scoping, and competitive positioning.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Delivery Lead",
        department: "Delivery",
        persona: "Hands-on engagement leader who ensures project quality and client satisfaction. Manages resources, timelines, and deliverables.",
        tools: ["list_projects", "create_project", "create_task", "update_task_status", "list_products", "get_product"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Knowledge Manager",
        department: "Research",
        persona: "Research and knowledge management expert who maintains the firm's intellectual capital. Creates frameworks, templates, and best practices.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["Revenue per Partner", "Win Rate", "Average Deal Size", "Utilization Rate", "Client NPS"],
    inventoryCategories: ["Frameworks", "Templates", "Research Reports", "Training Materials", "Tools"],
  },

  manufacturing: {
    id: "manufacturing",
    name: "Manufacturing",
    description: "Production business with inventory, quality control, supply chain, and equipment management",
    icon: "🏭",
    color: "from-gray-600 to-blue-600",
    departments: ["Executive", "Finance", "Sales", "Production", "Quality Control"],
    workers: [
      {
        name: "Sophia",
        role: "Plant Director",
        department: "Executive",
        persona: "Manufacturing leader focused on efficiency, quality, and safety. Balances production targets with cost optimization and team development.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Financial Controller",
        department: "Finance",
        persona: "Manufacturing finance expert tracking COGS, margin analysis, CapEx, and cash flow. Expert at costing models and procurement savings.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Sales Manager",
        department: "Sales",
        persona: "B2B sales professional managing key accounts, distribution channels, and order fulfillment. Strong at relationship building and forecasting.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Production Manager",
        department: "Production",
        persona: "Operations expert managing production schedules, raw materials, equipment maintenance, and workforce planning. Focused on OEE and continuous improvement.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Quality Manager",
        department: "Quality Control",
        persona: "Quality assurance leader ensuring product consistency and compliance. Manages inspections, certifications, and corrective actions.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["OEE", "Yield Rate", "Lead Time", "Defect Rate", "Inventory Turnover"],
    inventoryCategories: ["Raw Materials", "Work in Progress", "Finished Goods", "Packaging", "Spare Parts"],
  },

  insurance: {
    id: "insurance",
    name: "Insurance Agency",
    description: "Insurance agency managing policies, claims processing, underwriting, and customer renewals",
    icon: "🛡️",
    color: "from-indigo-600 to-blue-600",
    departments: ["Executive", "Finance", "Sales", "Claims", "Underwriting"],
    workers: [
      {
        name: "Sophia",
        role: "Agency Director",
        department: "Executive",
        persona: "Seasoned insurance leader who drives agency growth while maintaining strict compliance standards. Balances sales targets with risk management and customer satisfaction.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Compliance Manager",
        department: "Finance",
        persona: "Detail-oriented finance professional specializing in insurance accounting, premium reconciliation, and regulatory compliance. Ensures every dollar is tracked and every regulation met.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Insurance Sales Agent",
        department: "Sales",
        persona: "Trusted insurance advisor who builds long-term client relationships. Expert at needs analysis, policy recommendations, and renewal management. Consultative and persistent.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Claims Manager",
        department: "Claims",
        persona: "Methodical claims professional who processes claims efficiently and fairly. Manages documentation, investigations, and settlements with precision and empathy.",
        tools: ["list_projects", "create_project", "create_task", "update_task_status", "list_products", "get_product", "update_stock", "get_inventory_alerts", "get_inventory_valuation"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Underwriting Specialist",
        department: "Underwriting",
        persona: "Analytical underwriting expert who evaluates risk, sets premiums, and maintains policy documentation. Thorough, data-driven, and committed to sound risk assessment.",
        tools: ["list_documents", "get_document", "send_email", "list_emails", "list_projects", "create_task", "update_task_status"],
        is_manager: false,
      },
    ],
    kpis: ["Policies Sold", "Claim Ratio", "Premium Revenue", "Renewal Rate", "Customer Retention"],
    inventoryCategories: ["Auto Insurance", "Home Insurance", "Life Insurance", "Health Insurance", "Business Insurance", "Travel Insurance"],
  },

  realestate: {
    id: "realestate",
    name: "Real Estate Agency",
    description: "Real estate brokerage managing listings, showings, closings, and property management",
    icon: "🏠",
    color: "from-amber-600 to-yellow-600",
    departments: ["Executive", "Finance", "Sales", "Property Management", "Marketing"],
    workers: [
      {
        name: "Sophia",
        role: "Broker / Agency Director",
        department: "Executive",
        persona: "Experienced real estate broker who leads the agency with market insight and strategic vision. Builds a high-performing team and maintains top-tier client relationships.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Escrow Manager",
        department: "Finance",
        persona: "Real estate finance specialist managing commissions, escrow accounts, and agency cash flow. Expert at transaction accounting and compliance.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Senior Real Estate Agent",
        department: "Sales",
        persona: "Top-producing agent skilled at listing presentations, buyer consultations, and closing deals. Combines market knowledge with exceptional negotiation skills.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Property Manager",
        department: "Property Management",
        persona: "Organized property manager overseeing listings inventory, maintenance requests, and vendor coordination. Ensures properties are market-ready and well-maintained.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Marketing & Admin Director",
        department: "Marketing",
        persona: "Creative marketing professional who manages property listings, digital presence, and open house events. Keeps the agency organized and visible in the market.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["Listings", "Closed Deals", "Commission Revenue", "Avg Days on Market", "Lead Conversion"],
    inventoryCategories: ["Residential", "Commercial", "Land", "Rental", "Luxury"],
  },

  healthcare: {
    id: "healthcare",
    name: "Healthcare Clinic",
    description: "Medical clinic managing patient care, appointments, clinical operations, and medical supplies",
    icon: "🏥",
    color: "from-teal-600 to-cyan-600",
    departments: ["Executive", "Finance", "Patient Relations", "Clinical Operations", "Administration"],
    workers: [
      {
        name: "Sophia",
        role: "Clinic Director",
        department: "Executive",
        persona: "Healthcare administrator who balances patient care quality with operational efficiency. Committed to compliance, staff well-being, and continuous improvement.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Billing Manager",
        department: "Finance",
        persona: "Healthcare finance expert managing billing, insurance claims, and revenue cycle. Ensures accurate coding, timely collections, and financial health of the clinic.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Patient Relations Manager",
        department: "Patient Relations",
        persona: "Compassionate patient advocate who manages appointments, referrals, and patient communication. Focused on satisfaction, retention, and a seamless patient experience.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "log_customer_interaction", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Clinical Operations Lead",
        department: "Clinical Operations",
        persona: "Meticulous operations manager overseeing medical supplies, equipment, scheduling, and facility management. Ensures the clinic runs smoothly every day.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Administration & Compliance",
        department: "Administration",
        persona: "Organized administrator handling documentation, regulatory compliance, staff coordination, and internal communications. The backbone of clinic operations.",
        tools: ["list_documents", "get_document", "send_email", "list_emails", "list_projects", "create_task", "update_task_status"],
        is_manager: false,
      },
    ],
    kpis: ["Patient Volume", "Revenue per Visit", "Wait Time", "Satisfaction Score", "No-Show Rate"],
    inventoryCategories: ["Medications", "Medical Supplies", "Equipment", "Lab Materials", "PPE"],
  },

  logistics: {
    id: "logistics",
    name: "Logistics & Freight",
    description: "Logistics company managing fleet operations, warehousing, shipping contracts, and delivery tracking",
    icon: "🚛",
    color: "from-sky-600 to-blue-600",
    departments: ["Executive", "Finance", "Sales", "Fleet Operations", "Warehousing"],
    workers: [
      {
        name: "Sophia",
        role: "Operations Director",
        department: "Executive",
        persona: "Logistics veteran who optimizes the entire supply chain from pickup to delivery. Drives efficiency, reliability, and growth across all operations.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance Controller",
        department: "Finance",
        persona: "Logistics finance specialist tracking cost per shipment, fuel expenses, and route profitability. Expert at freight billing and vendor payment management.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Business Development Manager",
        department: "Sales",
        persona: "Driven BD professional who secures new shipping contracts and grows key accounts. Expert at rate negotiation, RFPs, and logistics consulting.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Fleet & Warehouse Manager",
        department: "Fleet Operations",
        persona: "Hands-on operations manager who tracks fleet utilization, warehouse capacity, route optimization, and equipment maintenance. Nothing moves without his oversight.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Documentation & Compliance",
        department: "Warehousing",
        persona: "Detail-oriented coordinator managing shipping documentation, customs compliance, and warehouse records. Ensures every shipment is properly documented and compliant.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["On-Time Delivery", "Cost per Shipment", "Fleet Utilization", "Warehouse Capacity", "Revenue per Route"],
    inventoryCategories: ["Vehicles", "Fuel", "Packaging", "Warehouse Equipment", "Safety Gear"],
  },

  lawfirm: {
    id: "lawfirm",
    name: "Law Firm",
    description: "Legal practice managing cases, client relations, billable hours, and legal research",
    icon: "⚖️",
    color: "from-slate-600 to-gray-600",
    departments: ["Executive", "Finance", "Client Relations", "Case Management", "Research"],
    workers: [
      {
        name: "Sophia",
        role: "Managing Partner",
        department: "Executive",
        persona: "Distinguished legal leader who steers the firm's strategy, maintains key client relationships, and upholds the highest professional standards.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Billing Director",
        department: "Finance",
        persona: "Legal finance expert managing trust accounts, billable hour tracking, and partner distributions. Meticulous with compliance and financial reporting.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Client Relations Partner",
        department: "Client Relations",
        persona: "Personable attorney who manages client intake, consultations, and relationship development. Expert at converting prospects into long-term clients.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Case Manager",
        department: "Case Management",
        persona: "Organized case manager who tracks deadlines, filings, court dates, and case progress. Ensures nothing falls through the cracks in a fast-paced legal environment.",
        tools: ["list_projects", "create_project", "create_task", "update_task_status", "list_products", "get_product", "get_inventory_alerts"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Legal Research & Knowledge Manager",
        department: "Research",
        persona: "Thorough legal researcher who maintains the firm's knowledge base, precedent library, and document templates. Analytical, resourceful, and intellectually curious.",
        tools: ["list_documents", "get_document", "send_email", "list_emails", "list_projects", "create_task", "update_task_status"],
        is_manager: false,
      },
    ],
    kpis: ["Billable Hours", "Cases Won", "Revenue per Attorney", "Client Acquisition Cost", "Case Cycle Time"],
    inventoryCategories: ["Case Files", "Legal Templates", "Research Reports", "Court Documents", "Contracts"],
  },

  accounting: {
    id: "accounting",
    name: "Accounting Firm",
    description: "Professional accounting firm providing tax, audit, and advisory services to businesses and individuals",
    icon: "📑",
    color: "from-green-600 to-emerald-600",
    departments: ["Executive", "Finance", "Client Services", "Tax", "Audit"],
    workers: [
      {
        name: "Sophia",
        role: "Managing Partner",
        department: "Executive",
        persona: "Strategic firm leader who balances client service excellence with business growth. Deep expertise in accounting standards and team development.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Operations Director",
        department: "Finance",
        persona: "Firm finance manager overseeing internal accounting, billing, partner distributions, and operational budgets. Practices what she preaches with impeccable books.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Client Acquisition & Relations Manager",
        department: "Client Services",
        persona: "Relationship-focused professional who grows the client base through referrals, networking, and exceptional service. Expert at scoping engagements and setting expectations.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Tax & Audit Operations Manager",
        department: "Tax",
        persona: "Detail-oriented operations lead managing tax filings, audit schedules, deliverables, and quality control. Ensures deadlines are met and work papers are thorough.",
        tools: ["list_projects", "create_project", "create_task", "update_task_status", "list_products", "get_product", "get_inventory_alerts", "get_inventory_valuation"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Knowledge & Compliance Manager",
        department: "Audit",
        persona: "Standards expert who maintains the firm's methodology, templates, and compliance documentation. Keeps the team updated on regulatory changes and best practices.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["Client Retention", "Revenue per Client", "Billable Rate", "Tax Filing Accuracy", "Turnaround Time"],
    inventoryCategories: ["Tax Returns", "Audit Reports", "Financial Statements", "Compliance Documents", "Advisory Reports"],
  },

  education: {
    id: "education",
    name: "Education / Training Center",
    description: "Educational institution managing enrollment, curriculum, student services, and learning outcomes",
    icon: "🎓",
    color: "from-violet-600 to-purple-600",
    departments: ["Executive", "Finance", "Enrollment", "Curriculum", "Student Services"],
    workers: [
      {
        name: "Sophia",
        role: "Director of Education",
        department: "Executive",
        persona: "Visionary education leader committed to student success and institutional growth. Balances academic excellence with operational sustainability.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Administration Director",
        department: "Finance",
        persona: "Education finance professional managing tuition, scholarships, budgets, and vendor payments. Ensures financial sustainability while maximizing student access.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Enrollment Director",
        department: "Enrollment",
        persona: "Energetic enrollment leader who drives student recruitment, admissions, and orientation. Expert at lead nurturing, campus tours, and conversion optimization.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Curriculum & Operations Manager",
        department: "Curriculum",
        persona: "Organized operations manager who handles course scheduling, learning materials, instructor coordination, and facility management. Keeps the academic engine running.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Student Services Director",
        department: "Student Services",
        persona: "Empathetic student advocate managing support services, counseling, events, and communications. Ensures every student feels supported throughout their journey.",
        tools: ["list_documents", "get_document", "send_email", "list_emails", "list_projects", "create_task", "update_task_status"],
        is_manager: false,
      },
    ],
    kpis: ["Enrollment Rate", "Completion Rate", "Student Satisfaction", "Revenue per Student", "Instructor Rating"],
    inventoryCategories: ["Courses", "Learning Materials", "Certifications", "Equipment", "Software Licenses"],
  },

  fitness: {
    id: "fitness",
    name: "Gym / Fitness Studio",
    description: "Fitness facility managing memberships, classes, trainers, and equipment",
    icon: "💪",
    color: "from-lime-600 to-green-600",
    departments: ["Executive", "Finance", "Membership Sales", "Fitness Operations", "Customer Experience"],
    workers: [
      {
        name: "Sophia",
        role: "General Manager",
        department: "Executive",
        persona: "Passionate fitness business leader who creates an inspiring environment for members and staff alike. Focused on growth, retention, and community building.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance Manager",
        department: "Finance",
        persona: "Fitness industry finance pro managing recurring revenue, membership billing, and operational costs. Expert at subscription economics and cash flow forecasting.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Membership Sales Director",
        department: "Membership Sales",
        persona: "High-energy sales leader who drives membership growth through tours, promotions, and referral programs. Knows how to convert prospects into committed members.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Fitness Operations Manager",
        department: "Fitness Operations",
        persona: "Hands-on operations manager overseeing class schedules, equipment maintenance, trainer coordination, and facility upkeep. Ensures a safe and well-equipped environment.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Customer Experience Manager",
        department: "Customer Experience",
        persona: "Member-focused professional who handles feedback, events, communications, and retention programs. Creates a welcoming atmosphere that keeps members coming back.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["Active Members", "Monthly Recurring Revenue", "Churn Rate", "Class Attendance", "PT Session Sales"],
    inventoryCategories: ["Equipment", "Supplements", "Merchandise", "Maintenance Supplies", "Cleaning Products"],
  },

  automotive: {
    id: "automotive",
    name: "Automotive Dealership",
    description: "Car dealership managing vehicle sales, financing, service center, and parts inventory",
    icon: "🚗",
    color: "from-red-600 to-rose-600",
    departments: ["Executive", "Finance", "Sales", "Service Center", "Parts & Inventory"],
    workers: [
      {
        name: "Sophia",
        role: "Dealership General Manager",
        department: "Executive",
        persona: "Automotive industry veteran who maximizes dealership performance across sales, service, and F&I. Drives a culture of customer satisfaction and profitability.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Insurance Manager",
        department: "Finance",
        persona: "Dealership F&I expert managing vehicle financing, insurance products, and dealership accounting. Maximizes per-deal profitability while ensuring compliance.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Sales Manager",
        department: "Sales",
        persona: "Charismatic sales leader who manages the showroom floor, test drives, and deal negotiations. Expert at vehicle presentation, financing options, and closing.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Service Center Manager",
        department: "Service Center",
        persona: "Technical operations manager overseeing vehicle repairs, parts ordering, service appointments, and warranty work. Ensures quality service and customer retention.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Customer Relations & Admin",
        department: "Parts & Inventory",
        persona: "Organized administrator managing customer follow-ups, documentation, CSI surveys, and dealership records. The glue that keeps the dealership running smoothly.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["Vehicles Sold", "Gross Profit per Unit", "Service Revenue", "Customer Satisfaction", "Inventory Turnover"],
    inventoryCategories: ["New Vehicles", "Used Vehicles", "Parts", "Accessories", "Service Supplies"],
  },

  construction: {
    id: "construction",
    name: "Construction Company",
    description: "Construction firm managing projects, bids, subcontractors, materials, and safety compliance",
    icon: "🏗️",
    color: "from-yellow-600 to-amber-600",
    departments: ["Executive", "Finance", "Business Development", "Project Management", "Safety & Compliance"],
    workers: [
      {
        name: "Sophia",
        role: "CEO / Principal",
        department: "Executive",
        persona: "Construction industry leader who balances project delivery with business growth. Deep expertise in construction management, client relations, and strategic planning.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Controller",
        department: "Finance",
        persona: "Construction finance expert managing job costing, progress billing, lien waivers, and cash flow. Expert at project budgets, change orders, and financial forecasting.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Business Development Director",
        department: "Business Development",
        persona: "Strategic BD professional who identifies opportunities, prepares bids, and nurtures client relationships. Expert at competitive positioning and contract negotiation.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Project Manager",
        department: "Project Management",
        persona: "Experienced construction PM who manages sites, timelines, resources, and subcontractors. Focused on on-time, on-budget delivery with zero safety incidents.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Safety & Compliance Officer",
        department: "Safety & Compliance",
        persona: "Dedicated safety professional managing OSHA compliance, safety training, incident reporting, and documentation. Ensures every worker goes home safe.",
        tools: ["list_documents", "get_document", "send_email", "list_emails", "list_projects", "create_task", "update_task_status"],
        is_manager: false,
      },
    ],
    kpis: ["Project Margin", "On-Time Completion", "Safety Incidents", "Backlog Value", "Subcontractor Performance"],
    inventoryCategories: ["Building Materials", "Heavy Equipment", "Safety Equipment", "Tools", "Temporary Structures"],
  },

  pharmacy: {
    id: "pharmacy",
    name: "Pharmacy / Drug Store",
    description: "Pharmacy managing prescriptions, OTC sales, inventory, expiry tracking, and regulatory compliance",
    icon: "💊",
    color: "from-cyan-600 to-teal-600",
    departments: ["Executive", "Finance", "Sales", "Pharmacy Operations", "Compliance"],
    workers: [
      {
        name: "Sophia",
        role: "Pharmacy Director",
        department: "Executive",
        persona: "Licensed pharmacist and business leader who ensures clinical excellence while growing the business. Balances patient care, regulatory compliance, and profitability.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance Manager",
        department: "Finance",
        persona: "Pharmacy finance specialist managing insurance reimbursements, vendor payments, and store profitability. Expert at PBM contracts and margin analysis.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Sales & Customer Relations Manager",
        department: "Sales",
        persona: "Customer-focused sales professional managing OTC promotions, loyalty programs, and community outreach. Builds lasting relationships with patients and healthcare providers.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Pharmacy Operations Manager",
        department: "Pharmacy Operations",
        persona: "Meticulous operations manager overseeing prescription fulfillment, inventory levels, expiry tracking, and supplier management. Ensures no stockout and no waste.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Regulatory Compliance Manager",
        department: "Compliance",
        persona: "Compliance expert managing DEA reporting, state board requirements, documentation, and staff certifications. Keeps the pharmacy audit-ready at all times.",
        tools: ["list_documents", "get_document", "send_email", "list_emails", "list_projects", "create_task", "update_task_status"],
        is_manager: false,
      },
    ],
    kpis: ["Prescriptions Filled", "Revenue per Customer", "Inventory Turnover", "Compliance Score", "Customer Retention"],
    inventoryCategories: ["Prescription Drugs", "OTC Medications", "Health Supplements", "Medical Devices", "Personal Care"],
  },

  travel: {
    id: "travel",
    name: "Travel Agency",
    description: "Travel agency managing bookings, tour operations, supplier relationships, and customer experiences",
    icon: "✈️",
    color: "from-pink-600 to-rose-600",
    departments: ["Executive", "Finance", "Sales", "Tour Operations", "Customer Service"],
    workers: [
      {
        name: "Sophia",
        role: "Agency Director",
        department: "Executive",
        persona: "Well-traveled agency leader with deep industry connections and a passion for creating unforgettable experiences. Drives growth through partnerships and innovation.",
        tools: ["delegate_to_worker", "query_worker", "summarize_department", "list_all_workers"],
        is_manager: true,
      },
      {
        name: "Ayşe",
        role: "Finance & Revenue Manager",
        department: "Finance",
        persona: "Travel finance expert managing commissions, supplier payments, customer deposits, and cash flow. Expert at pricing strategies and seasonal revenue forecasting.",
        tools: ["get_revenue_summary", "get_expense_summary", "get_profit_loss", "create_invoice", "list_invoices", "record_transaction", "get_cash_flow"],
        is_manager: false,
      },
      {
        name: "Marco",
        role: "Travel Sales Consultant",
        department: "Sales",
        persona: "Enthusiastic travel advisor who crafts perfect vacation packages, handles bookings, and builds repeat clientele. Expert at destination knowledge and upselling.",
        tools: ["list_customers", "get_customer", "create_customer", "update_customer_stage", "get_pipeline_summary", "log_customer_interaction", "get_sales_forecast", "send_email", "list_emails"],
        is_manager: false,
      },
      {
        name: "Kenji",
        role: "Tour Operations Manager",
        department: "Tour Operations",
        persona: "Logistics-minded operations manager who coordinates itineraries, supplier contracts, transportation, and on-ground services. Ensures every trip runs flawlessly.",
        tools: ["list_products", "get_product", "update_stock", "create_product", "get_inventory_alerts", "get_inventory_valuation", "list_projects", "create_project", "create_task", "update_task_status"],
        is_manager: false,
      },
      {
        name: "Elif",
        role: "Customer Service & Support Manager",
        department: "Customer Service",
        persona: "Warm and responsive support manager handling pre-trip questions, on-trip issues, and post-trip feedback. Turns every interaction into a positive experience.",
        tools: ["list_documents", "get_document", "send_email", "list_emails"],
        is_manager: false,
      },
    ],
    kpis: ["Bookings", "Revenue per Booking", "Customer Satisfaction", "Repeat Customer Rate", "Commission Revenue"],
    inventoryCategories: ["Flight Packages", "Hotel Bookings", "Tour Packages", "Car Rentals", "Travel Insurance", "Cruise Packages"],
  },
};

export function getTemplate(id: string): CompanyTemplate | undefined {
  return COMPANY_TEMPLATES[id];
}

export function getAllTemplates(): CompanyTemplate[] {
  return Object.values(COMPANY_TEMPLATES);
}
